### ISSUE TITLE
Set up Github action for releases

### ISSUE THREAD

**Issue by thomasahle** [thomasahle/tensorgrad#30]
It should do a number of things:
1. Push the latest code to AWS Lambda to run the Demo section on https://tensorcookbook.com/
2. Push the latest code to pypi using twine
3. Build the documentation and update https://tensorcookbook.com/docs/api/
4. Rebuild the cookbook.pdf and push that to the website.
5. Others?

One option is to have this as a manual github action, that we run from the website.

Another is to detect "version tagged" pushes to main, using something like this:
```
# Triggers on tag push matching "v*" pattern:
on:
  push:
    tags:
      - "v*"
```
